### ISSUE TITLE
2022.07.30

### ISSUE THREAD

**Issue by moonheekim0118** [moonheekim0118/today#1]
## 오늘 할 일 및 공부 계획
- [x] 프로젝트 누락된 타입 추가 및 타입 보강
- [x] CI/CD 및 젠킨스 공부  
- [ ] CI/CD 적용 시도
- [x] Theme 변수명 관리 개선 방안 찾아보기 (유명한 UI 라이브러리 조사)
- [x] useInfiniteQuery refetch 개선 방안 고민하기 
- [x] 전역 상태로 둘 것과 안 둘것 고민하기
- [x] 스토리북 다듬기

## 오늘 소확행
- [x] 지하철에서 책 읽깅 
- [x] 밥 끝내주게 맛있게 먹기
- [x] 저녁 산책 30분

**Comment by moonheekim0118** [comment]
**Theme 변수명 관리 개선 방안 찾아보기 (유명한 UI 라이브러리 조사)**

https://github.com/daangn/seed-design/blob/main/packages/design-token/src/colors/index.ts

당근마켓 디자인시스템은 이런식으루 한다.

color 네이밍은 가져가되, 자체를 수정한다.
대신 다크모드 되었을 때, color 자체가 바뀌는 경우는 background 이런식으로 잡아주는듯? 
이게 훨씬 간결해보이기도 하네

**Comment by moonheekim0118** [comment]
**useInfiniteQuery refetch 개선 방안 고민하기**

- refetch 보내는게 맞다. refetch 는 직전 요청을 보내기 때문에 정상적으로 이전 데이터가 그대로 보존된다.
- 근데 문제점은 ! 우리의 date 배열이 onSettle 전에 한 번 사라진다는것..

왜 사라지는가

- useMutation 함수 실행도 리렌더링을 트리거하기 때문이다. 그런데 Mutation 함수 실행 시에는 dateArray 가 당연히 꽉 차있음
        - why.. ? 여기에도 Loading , 상태가 있다는 것..
- 그래서 할 수 있는 방법은... dateArray 를 매 리렌더링마다 비워주는 것 ^_ㅠ

```tsx
  useEffect(() => {
    initializeDateArray();
  });
```


- 아니면, 서버에서 받아올 때 아예 Date 별로 끊어서 받아오게 요청하던가

**Comment by moonheekim0118** [comment]
**전역 상태로 둘 것과 안 둘것 고민하기**

- 전역 상태로 둘 것은 UI 데이터
- 서버데이터는 Query 로만 관리하기


`/feed/channelId/date`
일때 디폴트 ChannelId 가 Order 맨 위에 있는 것 때문에 고민하게 되었는데,
이를 해당 페이지 (/feed) 에서 요청 보내주거나, channelIist 및 order 를 리코일 전역상태로 관리해주는 것은 우아하지 못한 것 같음
일단 첫번째는, 분기 처리가 너무 많이 되고, 불필요한 서버 요청이 생김
두번째는 전역상태로 UI 데이터만 관리하는데 일관성을 헤치기도 하고, Channel list 를 계속해서 서버 상태와 동기화시켜줘야한다는 점이 매우 비효율적임.

따라서 내가 생각한 해결방법은.. 
channelId 쿼리 파람을 빈값으로 보내면, 서버에서 맨 위 order 에 있는 채널 메시지만 보내주는 것.
그러면 프론트엔드에서는 보여주기만 하면된다.

**Comment by moonheekim0118** [comment]
**CI/CD 젠킨스 공부**


### CI 예시
- 깃헙 액션 추가하여 특정 브랜치에 푸시될 때, 테스트 돌리도록 할 수 있음
- 이걸로 Jest 테스트 돌리고, Storybook 배포 자동화 하면 되지 않을까..? 
```
name: Front-End Cypress Tests

on:
  push:
    branches: ['**/front*']

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-18.04
    env:
      working-directory: ./frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Run browser & cypress
        run: npm run test
        working-directory: ${{ env.working-directory }}
```


### CD
대충 전체적인 플로우는 아래와 같은듯

1. EC2에 젠킨스 설치
2. 깃헙 웹훅 등록하여, 특정 브랜치에 푸시 될 때 젠킨스에 알려줌
3. 젠킨스에서 훅 실행되면, 깃헙 내 젠킨스 파일 찾아서 어떤 job 을 해줌 (아마도 build)
4. 젠킨스에서 job 이 완료 되면 이제 해당 빌드파일이 올라갈 EC2에 빌드파일 던져줌
5. EC2에서 빌드파일 받아서 서빙

- .env 관리는 깃헙 서브모듈로 한다구함
